language: perl

perl:
    - "5.8"
    - "5.14"
    - "5.18"
    - "5.20"

before_install:
    - cpanm App::FatPacker::Simple

install: ""
script:
    - stty cols 238
    - make
    - make check

notifications:
    recipients:
        - dave@goodell.io
    email:
        on_success: change
        on_failure: always
