language: perl

perl:
    - "5.8"
    - "5.14"
    - "5.18"
    - "5.20"

before_install:
    - cpanm --force App::FatPacker::Simple

install: ""
script:
    - stty cols 238
    - make
    - make check

after_failure:
  - "cat /home/travis/.cpanm/work/*/build.log"

notifications:
    email:
        recipients:
            - dave@goodell.io
        on_success: change
        on_failure: always
        recipients:
            - dave@goodell.io
