language: perl

perl:
    - "5.8"
    - "5.14"
    - "5.18"
    - "5.20"

before_install:
    - cpanm --force App::FatPacker::Simple

install: ""
script:
    - stty cols 238
    - make
    - make check

notifications:
    email:
        on_success: change
        on_failure: always
        recipients:
            - dave@goodell.io
